In [71]:
import numpy as np
#different ways to create an nd array:
#using array() function
a=np.array([1,2,3,4,5])
print(a," ",a.shape," ",a.ndim," ",a.dtype)
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b," ",b.shape," ",b.ndim)
#Creating 3-d arrays
#using zeroes() function
a=np.zeros((2,3))
print(a)
#using ones function
b=np.ones((3,4))
print(b," ",b.dtype)
#using empty() function. It creates an empty array without initialising its values to any particular value.
c=np.empty((2,3))
print(c," ",c.dtype)
#All the 3 functions ones(),zeros() and empty() take shape of an array as the argument
#It is not necessary that empty() will always return an array with zeroes as the value, sometimes it may 
#return an array with garbage values
d=np.empty((2,4))
print(d," ",d.dtype)
a=np.full((2,3),7)
print("arrays obtained from full: ",a)

[1 2 3 4 5]   (5,)   1   int64
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]   (3, 4)   2
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]   float64
[[0. 0. 0.]
 [0. 0. 0.]]   float64
[[4.4e-323 4.9e-323 5.4e-323 5.9e-323]
 [6.4e-323 6.9e-323 7.4e-323 7.9e-323]]   float64
arrays obtained from full:  [[7 7 7]
 [7 7 7]]


In [76]:
# when the dtype of an array is not specified, the datatype is set to float64(floating point) by default
a=np.array([1,2,3,4,5],dtype="int64")
print(a," ",a.ndim," ",a.dtype)
#asarray() converts the input to an array, but does not copy if the input in already an array
b=np.asarray(([1,2,3,4],[5,6,7,8]),dtype="int64")
print("b obtained after using asarray function: ",b)
c=np.asarray(((1,2,3),(4,5,6),(7,8,9)))
d=np.linspace(2,5,6)
print("After passing an array to asarray function: ",np.asarray(d))
print("c obtained after using asarray function: ",c)
#zeros_like(),ones_like() and empty_like create arrays of corresponding types according to the shape and 
#dtype of the arrays given in the input
print(np.zeros_like([[1,2,3,4],[5,6,7,8]]))
print(np.ones_like([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]))
print(np.empty_like([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]))

[1 2 3 4 5]   1   int64
b obtained after using asarray function:  [[1 2 3 4]
 [5 6 7 8]]
After passing an array to asarray function:  [2.  2.6 3.2 3.8 4.4 5. ]
c obtained after using asarray function:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0]
 [0 0 0 0]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
#np.arange() and np.linspace() is used to create 1-d arrays.
#arange() is the array equivalent version of the python built-in range() function which creates an array with the 
#values in the range specified as an input to the range function.
#linspace() is the function which creates an array with the no. of values specified equally spaced between the 
#starting and the ending position.
a=np.arange(10)
b=np.linspace(2,6,10)
print(a," ",a.ndim," ",a.shape)
print(b," ",b.ndim," ",b.shape)

[0 1 2 3 4 5 6 7 8 9]   1   (10,)
[2.         2.44444444 2.88888889 3.33333333 3.77777778 4.22222222
 4.66666667 5.11111111 5.55555556 6.        ]   1   (10,)


In [32]:
#2-d array creation functions are: eye(),diag() and vander()
#eye() gives the identity matrix(1 as the diagnol elements and rest are zero) of the specified shape
a=np.eye(3,4)
print(a)
#diag() creates an array with the given elements as diagnol elements and if an array is passed as as input,then a
#1-d array is returned with values as the diagnol elements of the passed 2-d array
b=np.diag([1,2,3,4])
print(b)
c=np.diag((1,2,3),2)
print(c)
d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Diagnol elements are:")
print(np.diag(d))
#vander(x,n) defines a vandermonte matrix as a 2-d numpy array
d=np.vander(np.arange(10),2)
d

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Diagnol elements are:
[ 1  6 11]


array([[0, 1],
       [1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1],
       [6, 1],
       [7, 1],
       [8, 1],
       [9, 1]])

In [36]:
#Arrays provide a way for batch operations on data without using any for loops.This is known as vectorization.
#In equal sized arrays, the operations are applied element wise.
#When arithmetic opeartions are applied between unequal sized arrays, it is known as broadcasting.
a=np.array([[1,2],[3,4],[5,6],[7,8]])
b=np.array([[9,10],[11,12],[13,14],[15,16]])
print("Sum: ",a+b)
print("Product: ",a*b)
print("Division: ",a/b)
print(1/b)
print(4*a)

Sum:  [[10 12]
 [14 16]
 [18 20]
 [22 24]]
Product:  [[  9  20]
 [ 33  48]
 [ 65  84]
 [105 128]]
Division:  [[0.11111111 0.2       ]
 [0.27272727 0.33333333]
 [0.38461538 0.42857143]
 [0.46666667 0.5       ]]
[[0.11111111 0.1       ]
 [0.09090909 0.08333333]
 [0.07692308 0.07142857]
 [0.06666667 0.0625    ]]
[[ 4  8]
 [12 16]
 [20 24]
 [28 32]]


In [51]:
#arithmetic operations
data=(((1,2),(4,5)),((6,7),(5,6)))
arr=np.array(data)
print(arr[:,1])
print(arr[0,:])
print("Shape: ",arr.shape," ","dimensions: ",arr.ndim,"size of the array: ",arr.size," ","datatype of the array: ",arr.dtype)
print(arr[1])
print(arr[-1,0,1])

[[4 5]
 [5 6]]
[[1 2]
 [4 5]]
Shape:  (2, 2, 2)   dimensions:  3 size of the array:  8   datatype of the array:  int64
[[6 7]
 [5 6]]
7


In [46]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr1[1])
print(arr1[:,1])
print(arr1[0,:])
print(arr1[-1])
print(arr1[-2])

[3 4]
[2 4 6 8]
[1 2]
[7 8]
[5 6]


In [52]:
arr2=np.array([[1,2],[3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [53]:
arr2[:,1]

array([2, 4])

In [55]:
arr2[0,:]

array([1, 2])

In [60]:
arr2[-2,1]

2

In [61]:
arr2[0][1]

2

In [63]:
arr2[-1][:]

array([3, 4])

In [5]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(np.add(a1,a2))
print(np.subtract(a1,a2))
print(np.multiply(a1,a2))
print(np.divide(a1,a2))
print(a1**2)
print(np.power(a1,a2))
print(np.power(a2,3))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 1  4]
 [ 9 16]]
[[    1    64]
 [ 2187 65536]]
[[125 216]
 [343 512]]


In [33]:
#joining arrays functions in numpy
#using concatenate function
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print("concatenation of 1-d arrays: ",np.concatenate((arr1,arr2),axis=0))
arr3=np.full((2,3),50)
arr4=np.ones((2,3))
print("arr3: ",arr3,"  ","arr4: ",arr4)
print("no. of dimensions in arr3: ",arr3.ndim)
print("concatenation of 2-d arrays: ",np.concatenate((arr3,arr4),axis=1))
#using append function
print("appending 1-d arrays: ",np.append(arr1,arr2))
print("appending 2-d arrays: ",np.append(arr3,arr4,axis=1))
#using insert function
print("insertion in 1-d arrays: ",np.insert(arr1,1,arr2))
print("insertion in 2-d arrays: ",np.insert(arr3,1,[4,5],axis=1))
print("insertion in 2-d arrays: ",np.insert(arr4,1,[4,5,6],axis=0))
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(7,8,9),(10,11,12)])
print("use of hstack: ",np.hstack((a,b)))
print("use of vstack: ",np.vstack((a,b)))
print("use of column stack: ",np.column_stack((a,b)))
print("use of stack: ",np.stack((a,b)))
print("use of dstack: ",np.dstack((a,b)))

concatenation of 1-d arrays:  [1 2 3 4 5 6 7 8]
arr3:  [[50 50 50]
 [50 50 50]]    arr4:  [[1. 1. 1.]
 [1. 1. 1.]]
no. of dimensions in arr3:  2
concatenation of 2-d arrays:  [[50. 50. 50.  1.  1.  1.]
 [50. 50. 50.  1.  1.  1.]]
appending 1-d arrays:  [1 2 3 4 5 6 7 8]
appending 2-d arrays:  [[50. 50. 50.  1.  1.  1.]
 [50. 50. 50.  1.  1.  1.]]
insertion in 1-d arrays:  [1 5 6 7 8 2 3 4]
insertion in 2-d arrays:  [[50  4 50 50]
 [50  5 50 50]]
insertion in 2-d arrays:  [[1. 1. 1.]
 [4. 5. 6.]
 [1. 1. 1.]]
use of hstack:  [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
use of vstack:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
use of column stack:  [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
use of stack:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
use of dstack:  [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [106]:
a=np.array([1,2,3,4,5,6])
print(a.reshape(2,3))
print(np.linspace(2,10,6).reshape(2,-1))
#logspace returns specified no. of points evenly spaced on a logarithmic scale
print(np.logspace(2,12,num=7,base=2))

[[1 2 3]
 [4 5 6]]
[[ 2.   3.6  5.2]
 [ 6.8  8.4 10. ]]
[4.00000000e+00 1.26992084e+01 4.03174736e+01 1.28000000e+02
 4.06374669e+02 1.29015916e+03 4.09600000e+03]


In [138]:
#fromiter creates a 1-d array from an iterable object providing data to fill the array.
#frombuffer creates a 1-d array from any buffer-like object.
buffer = b'\x01\x02\x03\x04\x05\x06\x07\x08'
# Create an array from the buffer, interpreting it as integers
a = np.frombuffer(buffer, dtype="int8")
print("interpreting a as an array",a)  # Output: [1 2 3 4 5 6 7 8]
b=b'Data science is a very important field'
print("interpreting b as an array",np.frombuffer(b,dtype="uint32",count=5))
a=range(10)
print(np.fromiter(a,dtype=np.int32,count=5))
iterable=(x**3 for x in range(10)) #list comprehension
print(np.fromiter(iterable,dtype="int64"))
l1=(i for i in range(0,12,3))
print(np.fromiter(l1,dtype="int32"))


interpreting a as an array [1 2 3 4 5 6 7 8]
interpreting b as an array [1635017028 1768125216 1701015141  544434464 1702240353]
[0 1 2 3 4]
[  0   1   8  27  64 125 216 343 512 729]
[0 3 6 9]


In [127]:
#numpy statistical functions
l1=[1,2,3,4,5] #list
print("mean of l1: ",np.mean(l1))
print("median of l1: ",np.median(l1))
print("std deviation of l1: ",np.std(l1))
print("variance of l1: ",np.var(l1))
print("25th quartile of l1",np.quantile(l1,q=0.25))
l2=[1,2,3,4,600]#list with an outlier
print("mean of l2: ",np.mean(l2))
print("median of l2: ",np.median(l2))
print("std deviation of l2: ",np.std(l2))
print("variance of l2: ",np.var(l2))
print("75th quartile of l2: ",np.quantile(l2,q=0.75))

mean of l1:  3.0
median of l1:  3.0
std deviation of l1:  1.4142135623730951
variance of l1:  2.0
25th quartile of l1 2.0
mean of l2:  122.0
median of l2:  3.0
std deviation of l2:  239.00209204105306
variance of l2:  57122.0
75th quartile of l2:  4.0


In [49]:
#different ways to create a series
#Series is a one-dimensional data structure that stores data of a similar kind. It is a column of a dataframe.
#A series does not have column lables as it is a single column of a dataframe. It does have row labels.
import pandas as pd
import numpy as np
s=pd.Series() #using empty series
print(s)
s1=pd.Series([1,2,3,4],name="class",dtype="float64") #using list
print(s1)
s2=pd.Series(np.array((1,2,3,4)),index=["1","2","3","4"]) #using an array
print(s2)
s3=pd.Series({"a":1,"b":2,"c":3,"d":4})  #using dictionary
print(s3)
print(s2.head(3))
print(s2.tail(3))
print(s2[2])
print(s3["b"])
print(s3[1:3])
print(s3[["a","b","c"]])
s4=pd.Series({1:"arun",2:"varun",3:"gobind"})


Series([], dtype: object)
0    1.0
1    2.0
2    3.0
3    4.0
Name: class, dtype: float64
1    1
2    2
3    3
4    4
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64
1    1
2    2
3    3
dtype: int64
2    2
3    3
4    4
dtype: int64
3
2
b    2
c    3
dtype: int64
a    1
b    2
c    3
dtype: int64


KeyError: 'arun'

In [16]:
import pandas as pd
import numpy as np
#A dataframe is a 2 dimensional data structure that stores data of different types including integer,floating point numbers,
#characters,strings etc. It is a tabular representation of data and is similar to a spreadsheet or a sql table.
#different ways of creating an array
#1. loading an excel file
# df=pd.read_excel(path)
# df=pd.DataFrame(df)
#2. loading data from a csv file
# df=pd.read_csv(path)
# df=pd.DtaFrame(df)
#3. using a dictionary
df=pd.DataFrame({"name":["ab","cd","ef"],"age":[21,30,25],"marks":[90,80,78]})
df["city"]=["delhi","shilong","mussorie"]
print(df)
#4 using a list of tuples
df=pd.DataFrame([(1,"a","delhi"),(2,"b","mumbai"),(3,"c","shilong")])
print("dataframe using a tuple: ",df)
print(df[2])

  name  age  marks      city
0   ab   21     90     delhi
1   cd   30     80   shilong
2   ef   25     78  mussorie
dataframe using a tuple:     0  1        2
0  1  a    delhi
1  2  b   mumbai
2  3  c  shilong
0      delhi
1     mumbai
2    shilong
Name: 2, dtype: object


In [31]:
import pandas as pd
import numpy as np
df=pd.DataFrame({"name":["ab","cd","ef"],"age":[21,30,25],"marks":[90,80,78]})
print(df.loc[[1,2]])
print(df.loc[df["name"]=="ab"])
print(df.iloc[1])
print(df.iloc[1:3,0:2])
print(df.loc[0:1])

  name  age  marks
1   cd   30     80
2   ef   25     78
  name  age  marks
0   ab   21     90
name     cd
age      30
marks    80
Name: 1, dtype: object
  name  age
1   cd   30
2   ef   25
  name  age  marks
0   ab   21     90
1   cd   30     80


In [39]:
arr1=np.array([(1,2),(3,4),(5,6),(7,8)])
arr2=np.array([(9,10),(11,12),(13,14),(15,16)])
print(np.sum(arr1,axis=0))
print(np.prod(arr1,axis=0))
print(np.cross(arr1,arr2))
print(np.transpose(arr2))


[16 20]
[105 384]
[-8 -8 -8 -8]
[[ 9 11 13 15]
 [10 12 14 16]]


In [50]:
import pandas as pd
import numpy as np

# Sample dataframe (replace this with your actual dataframe)
data = {
    'DayOfWeek': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    'Rainfall': [0.5, 0.8, 0.2, 0.0, 1.2, 0.7, 0.3]
}

df = pd.DataFrame(data)
print(df)

# Calculating statistics
maximum_rainfall = df['Rainfall'].max()
minimum_rainfall = df['Rainfall'].min()
q1_rainfall = df['Rainfall'].quantile(0.25)
q2_rainfall = df['Rainfall'].quantile(0.5)  # Median (Q2)
q3_rainfall = df['Rainfall'].quantile(0.75)
std_dev_rainfall = df['Rainfall'].std()

print("\nStatistics for Rainfall:")
print(f"Maximum Rainfall: {maximum_rainfall} inches")
print(f"Minimum Rainfall: {minimum_rainfall} inches")
print(f"Q1 (25th percentile): {q1_rainfall} inches")
print(f"Q2 (Median, 50th percentile): {q2_rainfall} inches")
print(f"Q3 (75th percentile): {q3_rainfall} inches")
print(f"Standard Deviation of Rainfall: {std_dev_rainfall} inches")


   DayOfWeek  Rainfall
0     Monday       0.5
1    Tuesday       0.8
2  Wednesday       0.2
3   Thursday       0.0
4     Friday       1.2
5   Saturday       0.7
6     Sunday       0.3

Statistics for Rainfall:
Maximum Rainfall: 1.2 inches
Minimum Rainfall: 0.0 inches
Q1 (25th percentile): 0.25 inches
Q2 (Median, 50th percentile): 0.5 inches
Q3 (75th percentile): 0.75 inches
Standard Deviation of Rainfall: 0.4070801956792859 inches
